config/routes.rb
Rails.application.routes.draw do
  root :to => 'index_page#index'
  get    '/signup',  to: 'users#new'
  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'
  resources :performances
  resources :budgets
  resources :contents
  resources :users
  resources :account_activations, only: [:edit]
  resources :password_resets,     only: [:new, :create, :edit, :update]

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/budget.rb
class Budget < ApplicationRecord
    belongs_to :content
    belongs_to :user
    validates :b_year, presence: true, :numericality => { :greater_than_or_equal_to => 0 } 
    validates :b_month, presence: true, :numericality => { :greater_than_or_equal_to => 0 } 
    validates :content_id, presence: true
    validates :b_money, presence: true, :numericality => { :greater_than_or_equal_to => 0 } 
end

app/controllers/budgets_controller.rb
class BudgetsController < ApplicationController
  before_action :set_budget, only: [:show, :edit, :update, :destroy]

  # GET /budgets
  # GET /budgets.json
  def index
    @content = Content.all
    @budgets = Budget.all
  end

  # GET /budgets/1
  # GET /budgets/1.json
  def show
  end

  # GET /budgets/new
  def new
    @content = Content.all.order(:name)
    @d = Date.today
    @year = @d.year.to_i
    @month = @d.month.to_i
    @budget = Budget.new
  end
  
  # POST /budgets
  # POST /budgets.json
  def create
    @content = Content.all
    @budget = Budget.new(budget_params)
    respond_to do |format|
      if @budget.save
        format.html { redirect_to root_path, notice: 'Budget was successfully created.' }
        format.json { render :show, status: :created, location: @budget }
      else
        format.html { render :new }
        format.json { render json: @budget.errors, status: :unprocessable_entity }
      end
    end
  end


  # DELETE /budgets/1
  # DELETE /budgets/1.json
  def destroy
    @budget.destroy
    respond_to do |format|
      format.html { redirect_to root_path, notice: 'Budget was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_budget
      @budget = Budget.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def budget_params
      params.require(:budget).permit(:b_year, :b_month, :b_money, :content_id, :b_comment)
    end
end

app/helpers/budgets_helper.rb
module BudgetsHelper
end

app/views/budgets/_form.html.erb
<%= form_with(model: budget, local: true) do |form| %>
  <% if budget.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(budget.errors.count, "error") %> prohibited this budget from being saved:</h2>

      <ul>
      <% budget.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :b_year %>
    <%= form.number_field :b_year, :value => @year %>
  </div>

  <div class="field">
    <%= form.label :b_month %>
    <%= form.number_field :b_month, :value => @month %>
  </div>

  <div class="field">
    <%= form.label :content_id %>
    <%= form.collection_select :content_id, @content, :id, :name %>
  </div>

  <div class="field">
    <%= form.label :b_money %>
    <%= form.number_field :b_money %>
  </div>

  <div class="field">
    <%= form.label :b_comment %>
    <%= form.text_field :b_comment %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/budgets/edit.html.erb
<h1>Editing Budget</h1>

<%= render 'form', budget: @budget %>

<%= link_to 'Show', @budget %> |
<%= link_to 'Back', budgets_path %>

app/views/budgets/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Budgets</h1>
<table>
  <thead>
    <tr>
      <th>year/month</th>
      <th>money</th>
      <th>content</th>
      <th class="comment">comment</th>
      <th></th>
    </tr>
  </thead>
  <tbody>
    <% @budgets.each do |budget| %>
      <tr>
        <td class="date"><%= budget.b_year %>/<%= budget.b_month %></td>
        <td class="money">￥<%= budget.b_money.to_s(:delimited) %></td>
        <td class="content"><%= budget.content.name %></td>
        <td class="comment"><%= budget.b_comment %></td>
        <td><%= link_to 'Destroy', budget, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>
<br>
<%= link_to 'New Budget', new_budget_path %>

app/views/budgets/new.html.erb
<h1>New Budget</h1>

<%= render 'form', budget: @budget %>

<%= link_to 'Back', budgets_path %>

app/views/budgets/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>B year:</strong>
  <%= @budget.b_year %>
</p>

<p>
  <strong>B month:</strong>
  <%= @budget.b_month %>
</p>

<p>
  <strong>B money:</strong>
  <%= @budget.b_money %>
</p>

<p>
  <strong>Content:</strong>
  <%= @budget.content_id %>
</p>

<p>
  <strong>B comment:</strong>
  <%= @budget.b_comment %>
</p>

<%= link_to 'Edit', edit_budget_path(@budget) %> |
<%= link_to 'Back', budgets_path %>