config/routes.rb
Rails.application.routes.draw do
  root :to => 'index_page#index'
  get    '/signup',  to: 'users#new'
  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'
  resources :performances
  resources :budgets
  resources :contents
  resources :users
  resources :account_activations, only: [:edit]
  resources :password_resets,     only: [:new, :create, :edit, :update]

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/performance.rb
class Performance < ApplicationRecord
    belongs_to :content
    belongs_to :user
    validates :p_year, presence: true, :numericality => { :greater_than_or_equal_to => 0 } 
    validates :p_month, presence: true, :numericality => { :greater_than_or_equal_to => 0 } 
    validates :p_day, presence: true, :numericality => { :greater_than_or_equal_to => 0 } 
    validates :content_id, presence: true
    validates :p_money, presence: true, :numericality => { :greater_than_or_equal_to => 0 } 
end

app/controllers/performances_controller.rb
class PerformancesController < ApplicationController
  before_action :set_performance, only: [:show, :edit, :update, :destroy]

  # GET /performances
  # GET /performances.json
  def index
    @content = Content.all
    @performances = Performance.all
  end

  # GET /performances/1
  # GET /performances/1.json
  def show
  end

  # GET /performances/new
  def new
    @content = Content.all
    @d = Date.today
    @year = @d.year.to_i
    @month = @d.month.to_i
    @day = @d.day.to_i
    @performance = Performance.new
  end

  # POST /performances
  # POST /performances.json
  def create
    @content = Content.all
    @d = Date.today
    @year = @d.year.to_i
    @month = @d.month.to_i
    @day = @d.day.to_i

    @performance = Performance.new(performance_params)
    respond_to do |format|
      if @performance.save
        format.html { redirect_to root_path, notice: 'Performance was successfully created.' }
        format.json { render :show, status: :created, location: @performance }
      else
        format.html { render :new }
        format.json { render json: @performance.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @performance.destroy
    respond_to do |format|
      format.html { redirect_to root_path, notice: 'Performance was successfully destroyed.' }
      format.json { head :no_content }
    end
  end
  
  private
    # Use callbacks to share common setup or constraints between actions.
    def set_performance
      @performance = Performance.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def performance_params
      params.require(:performance).permit(:p_year, :p_month, :p_day, :p_money, :content_id, :p_comment)
    end
end

app/helpers/performances_helper.rb
module PerformancesHelper
end

app/views/performances/_form.html.erb
<%= form_with(model: performance, local: true) do |form| %>
  <% if performance.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(performance.errors.count, "error") %> prohibited this performance from being saved:</h2>

      <ul>
      <% performance.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :p_year %>
    <%= form.number_field :p_year, :value => @d.year %>
  </div>

  <div class="field">
    <%= form.label :p_month %>
    <%= form.number_field :p_month, :value => @d.month %>
  </div>

  <div class="field">
    <%= form.label :p_day %>
    <%= form.number_field :p_day, :value => @d.day %>
  </div>

  <div class="field">
    <%= form.label :content_id %>
    <%= form.collection_select :content_id, Content.all, :id, :name %>
  </div>

  <div class="field">
    <%= form.label :p_money %>
    <%= form.number_field :p_money %>
  </div>

  <div class="field">
    <%= form.label :p_comment %>
    <%= form.text_field :p_comment %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/performances/edit.html.erb
<h1>Editing Performance</h1>

<%= render 'form', performance: @performance %>

<%= link_to 'Show', @performance %> |
<%= link_to 'Back', performances_path %>

app/views/performances/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Performances</h1>

<table>
  <thead>
    <tr>
      <th>year/month/day</th>
      <th>money</th>
      <th>Content</th>
      <th class="comment">comment</th>
      <th></th>
    </tr>
  </thead>
  <tbody>
    <% @performances.each do |performance| %>
      <tr>
        <td class="date"><%= performance.p_year %>/<%= performance.p_month %>/<%= performance.p_day %></td>
        <td class="money">￥<%= performance.p_money.to_s(:delimited) %></td>
        <td class="content"><%= performance.content.name %></td>
        <td class="comment"><%= performance.p_comment %></td>
        <td><%= link_to 'Destroy', performance, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>
<br>
<%= link_to 'New Performance', new_performance_path %>

app/views/performances/new.html.erb
<h1>New Performance</h1>

<%= render 'form', performance: @performance %>

<%= link_to 'Back', performances_path %>

app/views/performances/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>P year:</strong>
  <%= @performance.p_year %>
</p>

<p>
  <strong>P month:</strong>
  <%= @performance.p_month %>
</p>

<p>
  <strong>P day:</strong>
  <%= @performance.p_day %>
</p>

<p>
  <strong>P money:</strong>
  <%= @performance.p_money %>
</p>

<p>
  <strong>Content:</strong>
  <%= @performance.content_id %>
</p>

<p>
  <strong>P comment:</strong>
  <%= @performance.p_comment %>
</p>

<%= link_to 'Edit', edit_performance_path(@performance) %> |
<%= link_to 'Back', performances_path %>